---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 482816889974.dkr.ecr.eu-west-1.amazonaws.com/build_env
    aws_access_key_id: {{aws_access_key_id}}
    aws_secret_access_key: {{aws_secret_access_key}}


run:
  path: bash
  args: [/home/steve/hello.sh]
