platform: linux

image_resource:
  type: docker-image
  source:
    repository: 482816889974.dkr.ecr.eu-west-1.amazonaws.com/build_env
    tag: latest
    aws_access_key_id: {{aws_access_key_id}}
    aws_secret_access_key: {{aws_secret_access_key}}

inputs:
- name: code

outputs:
- name: app

run:
  path:
    code/complete/ci/scripts/docker-prepare.sh
