resources:

- name: opp-repo
  type: git
  source:
    branch: master
    private_key: {{git-private-key}}
    uri: git@github.com:stuntmansteve/gs-rest-service.git

- name: grs-image
  type: docker-image
  source:
    repository: 482816889974.dkr.ecr.eu-west-1.amazonaws.com/gs-rest-service
    aws_access_key_id: {{aws_access_key_id}}
    aws_secret_access_key: {{aws_secret_access_key}}

jobs:

  - name: push-to-ecs
    plan:
      - do:
          - get: opp-repo
          - task: package
            file: opp-repo/complete/ci/tasks/docker-prepare.yml
            input_mapping:
              code: opp-repo
          - put: grs-image
            params:
              build: app
              tag: app/version.txt
              tag_as_latest: true
            get_params:
              skip_download: true
